### ISSUE TITLE
Stop running Rust tests in CI for all Java and Spark versions

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#1480]
### What is the problem the feature request solves?

The rust tests do not use Java or Spark so we do not need to run them for different Java and Spark version.

We currently have this matrix:

```
  linux-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java_version: [8, 11, 17]
        test-target: [rust, java]
        spark-version: ['3.5']
        scala-version: ['2.12', '2.13']
```

We should move the Rust tests to a different job to reduce duplication of running these tests.
